### ISSUE TITLE
Incidencia: Eliminar workflow docker

### ISSUE THREAD

**Issue by guaridpin** [EGC-G2-tortilla/tortilla-hub#161]
**Descripción**: El workflow destinado a la creación de una imagen en docker y su arranque inmediato debe eliminarse por no funcionar como se esperaba.
**Criterios de Aceptación**: Eliminar el workflow y levantar la imagen de la forma original.

**Fecha Límite**: M2.3 - Seguimiento de integración 18/12/2024

**Comment by antoniommff** [comment]
Esta incidencia se ha decidido marcar como concluída ya que finalmente no va a hacer falta eliminar el workflow por dos motivos: por un lado, tras consultar con el profesor nos han dicho que si mantenemos el workflow se nos podrá valorar de alguna forma ya que aunque no tiene funcionalidad funciona correctamente; por otro lado, pretendemos usar una raspberry pi para desplegar la imagen de docker y que así el workflow tenga funcionalidad.
