### ISSUE TITLE
Incidencia: Error con el servidor codacy y 20 nuevos Issues

### ISSUE THREAD

**Issue by rgavira123** [EGC-G2-tortilla/tortilla-hub#254]
En la PR diaria de mergeo a main se ha encontrado un error en el worflow del codacy, en principio es un fallo del servidor
![image](https://github.com/user-attachments/assets/3d058bb4-0bb9-4212-9289-46c48263c153)

Además también han aparecido de repente 20 nuevas issues de codacy tras el commit de @antoniommff, es prioritario que se resuelvan estos conflictos antes del mergeo a main.
![image](https://github.com/user-attachments/assets/1b821514-f220-4227-9519-27140d62de59)

_Originally posted by @rgavira123 in https://github.com/EGC-G2-tortilla/tortilla-hub/issues/251#issuecomment-2544957892_

Se espera que el error con el servidor no tenga que ver con nosotros y la siguiente vez que se ejecute funcione correctamente

**Comment by DelfinSR** [comment]
Deberíamos de aprovechar para solucionar algumos de los errores que reporta codacy.
![image](https://github.com/user-attachments/assets/950b2e23-41d1-4802-8871-1da48e223e98)
